version: "2"
services:
  jupyterlab:
    build:
      context: .
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "./dl4us:/home/jovyan/work"
    environment:
      NB_UID: 500
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --notebook-dir=/home/jovyan/work